
import Link from "next/link";
import "./globals.css";
import { UserContextProvider } from '@/context/UserContext'
import { AuthProvider } from '@/context/AuthContext';
import Header from "@/components/Header";
import { AlertProvider } from "@/context/AlertContext";
import Alert from "@/components/Alert";
import Drawer from "@/components/Drawer";
import { DrawerProvider } from "@/context/DrawerContext";
import Navbar from "@/components/Navbar";
import { ModalProvider } from "@/context/ModalContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="lemonade">
      <head>

        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
      </head>
      <body className="bg-ifms">
        <DrawerProvider>
          <Navbar />
          <Drawer>
            <ModalProvider>
              <AlertProvider>
                <AuthProvider>
                  <Alert />
                  {children}

                </AuthProvider>
              </AlertProvider>
            </ModalProvider>
          </Drawer>
        </DrawerProvider>






      </body>

    </html>
  );
}
